<a href="https://colab.research.google.com/github/pabloyss/CPD/blob/main/Aprendizado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from google.colab import files
uploaded = files.upload()

Saving TestingData_2F_Original.txt to TestingData_2F_Original.txt
Saving TrainingData_2F_Original.txt to TrainingData_2F_Original.txt


In [9]:
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np
from google.colab import data_table
from sklearn.metrics import accuracy_score


NormData = pd.read_csv('TrainingData_2F_Norm.txt', sep="\t", header=0)
OrigData = pd.read_csv('TrainingData_2F_Original.txt', sep="\t", header=0)
TestOrig = pd.read_csv('TestingData_2F_Original.txt', sep="\t", header=0)
TestNorm = pd.read_csv('TestingData_2F_Norm.txt', sep="\t", header=0)

In [7]:
# Norm Data
NormData = NormData.drop('ID', axis=1)
x = NormData["total.sulfur.dioxide"]
x = x.values
x1 = NormData["citric.acid"]
x1 = x1.values
y = NormData["Class"]
y = y.values

X = list(zip(x,x1))

neigh = KNeighborsClassifier(n_neighbors=7)
neigh.fit(X, y)

# Train Model

x = TestNorm["total.sulfur.dioxide"]
x = x.values
x1 = TestNorm["citric.acid"]
x1 = x1.values

y = TestNorm["Class"]
y = y.values
Xt = list(zip(x,x1))

print(neigh.predict(Xt))

print(accuracy_score(TestNorm["Class"], neigh.predict(Xt)))



[0 0 1 1]
1.0


In [17]:
# Orig Data
x = OrigData["total.sulfur.dioxide"]
x = x.values
x1 = OrigData["citric.acid"]
x1 = x1.values
y = OrigData["class"]
y = y.values

X = list(zip(x,x1))

neigh = KNeighborsClassifier(n_neighbors=7)
neigh.fit(X, y)

# Train Model

x = TestOrig["total.sulfur.dioxide"]
x = x.values
x1 = TestOrig["citric.acid"]
x1 = x1.values

y = TestOrig["class"]
y = y.values
Xt = list(zip(x,x1))

print(neigh.predict(Xt))

print(accuracy_score(TestOrig["class"], neigh.predict(Xt)))

N1 = [26, 0]

neighbors = neigh.kneighbors([N1], n_neighbors = 25, return_distance=True)

print(neighbors)
neighbors = neigh.kneighbors([N1], n_neighbors = 5, return_distance=False)

neighbors_to_list = neighbors.flatten().tolist()
neighbors_to_list.sort()

print(neighbors_to_list)









[1 1 1 0]
0.25
(array([[ 0.4       ,  1.00005   ,  1.11359777,  2.01434853,  4.00005   ,
         4.04474968,  5.00048998,  5.00675544,  8.00039999,  8.00330557,
         8.00901992,  8.01379436,  8.02246845,  9.00979467, 10.01011988,
        11.00089087, 13.00471068, 13.00923134, 14.00080355, 14.00822615,
        14.00857238, 15.00001333, 16.00007812, 17.00004706, 17.0070603 ]]), array([[20, 26, 29, 24, 10,  6, 39,  8, 15, 38,  5, 25,  7, 34, 40, 19,
         4, 28, 18, 27, 43, 14, 32, 17, 13]]))
[10, 20, 24, 26, 29]


0.4       , 1.00005   , 1.11359777, 2.01434853, 4.00005

0.75 0.5

0.5 0.25

0.25 0.75

0.25 1.0